/**
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.textedit.common.xtext.generator;

@SuppressWarnings("all")
public class UmlCommonGenerator /* implements IGenerator  */{
  public void doGenerate(final /* Resource */Object resource, final /* IFileSystemAccess */Object fsa) {
  }
}
