/*****************************************************************************
 * Copyright (c) 2015 CEA LIST.
 *
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *  Jeremie Tatibouet (CEA LIST)
 *
 *****************************************************************************/
package org.eclipse.papyrus.moka.fuml.statemachines.Semantics.StateMachines.BehaviorStateMachines.Selection;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.eclipse.papyrus.moka.fuml.Semantics.CommonBehaviors.Communications.EventOccurrence;
import org.eclipse.papyrus.moka.fuml.Semantics.CommonBehaviors.Communications.SignalEventOccurrence;
import org.eclipse.papyrus.moka.fuml.statemachines.Semantics.StateMachines.BehaviorStateMachines.TransitionActivation;
import org.eclipse.papyrus.moka.fuml.statemachines.Semantics.StateMachines.BehaviorStateMachines.VertexActivation;
import org.eclipse.papyrus.moka.fuml.statemachines.Semantics.StateMachines.BehaviorStateMachines.Communications.CompletionEventOccurrence;
import org.eclipse.papyrus.moka.fuml.statemachines.Semantics.StateMachines.BehaviorStateMachines.Configuration.StateMachineConfiguration;

public class DefaultTransitionSelectionStrategy extends TransitionSelectionStrategy {
	
	public List<TransitionActivation> selectTransitions(StateMachineConfiguration configuration, EventOccurrence eventOccurrence) {
		// Find for the given configuration the set of transition that can fire.
		// The search starts from the deepest level. If no transition enabled are found at this level
		// then the search continue in the upper level. The search stops when at given level a not empty
		// set of enabled transition is calculated. Transition returned are only those that are not triggered by an event 
		// (i.e. Transitions that are automatic or only guarded).
		List<TransitionActivation> fireableTransition = new ArrayList<TransitionActivation>();
		Map<Integer, List<VertexActivation>> cartography = configuration.getCartography();
		int i = cartography.size();
		boolean nextLevel = true;
		while(i >= 1 && nextLevel){
			for(VertexActivation vertexActivation : cartography.get(i)){
				for(TransitionActivation transitionActivation : vertexActivation.getOutgoingTransitions()){
					if(this.isFireable(transitionActivation, eventOccurrence)){
						fireableTransition.add(transitionActivation);
					}
				}
			}
			if(!fireableTransition.isEmpty()){
				nextLevel = false;
			}else{
				i--;
			}
		}
		return fireableTransition;
	}
	
	protected boolean isFireable(TransitionActivation transitionActivation, EventOccurrence eventOccurrence){
		// A transition is reactive when:
		//
		// 	- A completion event is being dispatched and this transition has no trigger
		// 	  but its eventual guard evaluates to true.
		//	  Note: the scope of a completion event is the state from which it was 
		//
		//  - A signal event is being dispatched and this transition has a trigger
		//    that matches the signal and its eventual guard evaluates to true
		boolean reactive = true;
		if(eventOccurrence instanceof CompletionEventOccurrence){
			reactive = !transitionActivation.isTriggered() && // The transition declares not explicit trigger(s)
						transitionActivation.getSourceActivation()==((CompletionEventOccurrence)eventOccurrence).stateActivation && // The event was generated by a state activation which is the source ot this transition
						transitionActivation.evaluateGuard(); // The guard of the transition evaluates to true
		}else if(eventOccurrence instanceof SignalEventOccurrence){
			reactive = transitionActivation.hasTrigger(((SignalEventOccurrence)eventOccurrence).signalInstance) && // the transition declares a trigger for that matches the event
					   transitionActivation.evaluateGuard(); // The guard of the transition evaluates to true
		}else{
			reactive = false;
		}
		return reactive;
	}
}
