<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="B2MML_ProcessSegment" nsURI="http://papyrus/B2MML" nsPrefix="B2MML_ProcessSegment">
  <eClassifiers xsi:type="ecore:EClass" name="ProcessSegmentInformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processsegment" ordered="false"
        lowerBound="1" eType="#//ProcessSegment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Activity" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../../org.eclipse.uml2.uml/model/UML.ecore#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessSegment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Action" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../../org.eclipse.uml2.uml/model/UML.ecore#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processsegment" ordered="false"
        upperBound="-1" eType="#//ProcessSegment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Behavior" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../../org.eclipse.uml2.uml/model/UML.ecore#//Behavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessSegmentParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="PersonnelSegmentSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="EquipmentSegmentSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalAssetSegmentSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="MaterialSegmentSpecification"/>
  <eSubpackages name="ProductionSchedule" nsURI="http:///B2MML_ProcessSegment/ProductionSchedule.ecore"
      nsPrefix="B2MML_ProcessSegment.ProductionSchedule">
    <eClassifiers xsi:type="ecore:EClass" name="ProductionSchedule">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Artifact" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../../org.eclipse.uml2.uml/model/UML.ecore#//Artifact"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProductionRequest">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Artifact" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../../org.eclipse.uml2.uml/model/UML.ecore#//Artifact"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
