<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="syncmapping" nsURI="http://www.eclipse.org/papyrus/2015/syncmapping"
    nsPrefix="syncmapping">
  <eClassifiers xsi:type="ecore:EDataType" name="One" instanceClassName="org.eclipse.papyrus.aof.core.IOne">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Mapping" instanceClassName="org.eclipse.papyrus.aof.sync.IMapping">
    <eTypeParameters name="F"/>
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingInstance">
    <eTypeParameters name="F"/>
    <eTypeParameters name="T"/>
    <eOperations name="addConsequent" ordered="false" lowerBound="1">
      <eParameters name="consequent" ordered="false" lowerBound="1">
        <eGenericType eClassifier="#//IMappingInstance">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="destroy" ordered="false" lowerBound="1"/>
    <eOperations name="iterator" ordered="false" lowerBound="1">
      <eGenericType eClassifier="#//Iterator">
        <eTypeArguments eClassifier="#//IMappingInstance">
          <eTypeArguments/>
          <eTypeArguments/>
        </eTypeArguments>
      </eGenericType>
    </eOperations>
    <eOperations name="eBasicSetContainer" ordered="false" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedVisibility" value="true"/>
      </eAnnotations>
      <eParameters name="newContainer" ordered="false" lowerBound="1" eType="#//InternalEObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1">
      <eGenericType eClassifier="#//Mapping">
        <eTypeArguments eTypeParameter="#//MappingInstance/F"/>
        <eTypeArguments eTypeParameter="#//MappingInstance/T"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="left" ordered="false" lowerBound="1">
      <eGenericType eClassifier="#//One">
        <eTypeArguments eTypeParameter="#//MappingInstance/F"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="right" ordered="false"
        lowerBound="1">
      <eGenericType eClassifier="#//One">
        <eTypeArguments eTypeParameter="#//MappingInstance/T"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consequent" ordered="false"
        upperBound="-1" containment="true">
      <eGenericType eClassifier="#//IMappingInstance">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tracker" ordered="false"
        lowerBound="1" eType="#//ObserverTracker"/>
    <eGenericSuperTypes eClassifier="#//InternalInstance">
      <eTypeArguments eTypeParameter="#//MappingInstance/F"/>
      <eTypeArguments eTypeParameter="#//MappingInstance/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMappingInstance" instanceClassName="org.eclipse.papyrus.aof.sync.IMapping$Instance"
      abstract="true" interface="true">
    <eTypeParameters name="F"/>
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ObserverTracker" instanceClassName="org.eclipse.papyrus.aof.core.utils.ObserverTracker"/>
  <eClassifiers xsi:type="ecore:EClass" name="InternalInstance" instanceClassName="org.eclipse.papyrus.aof.sync.AbstractMapping$InternalInstance"
      abstract="true" interface="true" eSuperTypes="#//IMappingInstance">
    <eTypeParameters name="F"/>
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Iterator" instanceClassName="java.util.Iterator">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalEObject" instanceClassName="org.eclipse.emf.ecore.InternalEObject"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappingModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" ordered="false"
        upperBound="-1" containment="true">
      <eGenericType eClassifier="#//IMappingInstance">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
