<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="expansionmodel" nsURI="http:///expansionmodel.ecore" nsPrefix="expansionmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Representation" eSuperTypes="#//AbstractRepresentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="graphicalElementType" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inducedRepresentations"
        ordered="false" upperBound="-1" eType="#//InducedRepresentation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subRepresentations" ordered="false"
        upperBound="-1" eType="#//Representation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRepresentation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editPartQualifiedName"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind" ordered="false" eType="#//RepresentationKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewFactory" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepresentationKind">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editPartQualifiedName"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewFactory" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InducedRepresentation" eSuperTypes="#//AbstractRepresentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hint" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" ordered="false"
        upperBound="-1" eType="#//Representation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representationkinds" ordered="false"
        upperBound="-1" eType="#//RepresentationKind" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representations" ordered="false"
        upperBound="-1" eType="#//AbstractRepresentation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UseContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DiagramType" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representations" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Representation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GmftRepresentations" ordered="false"
        upperBound="-1" eType="#//GMFT_Based_Representation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GMFT_Based_Representation" eSuperTypes="#//Representation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reusedID" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramExpansion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usages" ordered="false"
        upperBound="-1" eType="#//UseContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" ordered="false"
        upperBound="-1" eType="#//Library" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
