/**
 *
 * $Id$
 */
package org.eclipse.papyrus.aof.emf.samples.population.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.papyrus.aof.emf.samples.population.Person;

/**
 * A sample validator interface for {@link org.eclipse.papyrus.aof.emf.samples.population.Population}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PopulationValidator {
	boolean validate();

	boolean validatePersons(EList<Person> value);
}
