<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="umlexpressions" nsURI="http://www.eclipse.org/papyrus/umlexpressions"
    nsPrefix="umlexpressions">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="UMLExpressions"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="IsStereotypedWithExpression" eSuperTypes="../../org.eclipse.papyrus.infra.emf.expressions/model/expressions.ecore#//booleanexpressions/IBooleanEObjectExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This expression to use to ckech if a UML object is stereotyped with the expected stereotype.&#xD;&#xA;The evaluate method returns TRUE when the object is stereotyped by the stereotype identified by its qualified and when the stereotype comes from a profile with the sasme URI profile has expected.&#xD;&#xA;URI profile field is not mandatory for the test."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotypeQualifiedName"
        ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The qualified name of the required stereotype."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profileURI" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The URI of the profile owning the stereotype.&#xD;&#xA;The URI can be null or empty. In this case, we don't check the URI of the profile providing the Stereotype."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasAppliedStereotypesExpression" eSuperTypes="../../org.eclipse.papyrus.infra.emf.expressions/model/expressions.ecore#//booleanexpressions/IBooleanEObjectExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This expressions tests is stereotypes are applied on the object.&#xD;&#xA;The evaluate method returns TRUE if at least one Stereotype is applied on the object.&#xD;&#xA;The evaluate method returns FALSE if no Stereotype is applied on the object.&#xD;&#xA;The evaluate method returns FALSE when the argument is NULL.&#xD;&#xA;The evaluate method returns FALSE when the argument is not an instance of UML::Element"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsTypeOfExpression" eSuperTypes="../../org.eclipse.papyrus.infra.emf.expressions/model/expressions.ecore#//booleanexpressions/IBooleanEObjectExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>The evaluate methods returns True if the argument&amp;nbsp;has the&amp;nbsp;same type thant the excepted metaclass.&lt;/p>&#xA;&#xA;&lt;p>If the metaclass is not defined, the evaluate method returns False.&lt;/p>&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umlEClass" ordered="false"
        eType="ecore:EClass ../../org.eclipse.papyrus.infra.emf.expressions/model/expressions.ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsKindOfExpression" eSuperTypes="../../org.eclipse.papyrus.infra.emf.expressions/model/expressions.ecore#//booleanexpressions/IBooleanEObjectExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>The evaluate methods returns True if the arguments is an instance of the expected metaclass.&lt;/p>&#xA;&#xA;&lt;p>If the metaclass is not defined, the evaluate method returns False.&lt;/p>&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="umlEClass" ordered="false"
        eType="ecore:EClass ../../org.eclipse.papyrus.infra.emf.expressions/model/expressions.ecore#//EClass"/>
  </eClassifiers>
</ecore:EPackage>
