/**
 * Copyright (c) 2015 CEA LIST and others.
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *   CEA LIST - Initial API and implementation
 * 
 */
package org.eclipse.papyrus.papyrusgmfgenextension;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generate Using Element Type Creation Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.papyrus.papyrusgmfgenextension.PapyrusgmfgenextensionPackage#getGenerateUsingElementTypeCreationCommand()
 * @model annotation="http://www.eclipse.org/emf/2002/GenModel Documentation='flag that indicated if the code generation should rely on the creation command generated by gmf tooling of the creation commands based on UML.edit framework'"
 * @generated
 */
public interface GenerateUsingElementTypeCreationCommand extends CommentedElement {
} // GenerateUsingElementTypeCreationCommand
