package org.eclipse.papyrus.manufacturing.ofbiz.createWorkEffort;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-09-08T11:16:57.464+02:00
 * Generated source version: 3.1.1
 * 
 */
@WebServiceClient(name = "createWorkEffort", 
                  wsdlLocation = "http://localhost:8080/manufacturing/control/SOAPService/createWorkEffort?wsdl",
                  targetNamespace = "http://ofbiz.apache.org/service/") 
public class CreateWorkEffort extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ofbiz.apache.org/service/", "createWorkEffort");
    public final static QName CreateWorkEffortPort = new QName("http://ofbiz.apache.org/service/", "createWorkEffortPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/manufacturing/control/SOAPService/createWorkEffort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreateWorkEffort.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/manufacturing/control/SOAPService/createWorkEffort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreateWorkEffort(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreateWorkEffort(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateWorkEffort() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CreateWorkEffort(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreateWorkEffort(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreateWorkEffort(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CreateWorkEffortPortType
     */
    @WebEndpoint(name = "createWorkEffortPort")
    public CreateWorkEffortPortType getCreateWorkEffortPort() {
        return super.getPort(CreateWorkEffortPort, CreateWorkEffortPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateWorkEffortPortType
     */
    @WebEndpoint(name = "createWorkEffortPort")
    public CreateWorkEffortPortType getCreateWorkEffortPort(WebServiceFeature... features) {
        return super.getPort(CreateWorkEffortPort, CreateWorkEffortPortType.class, features);
    }

}
