package org.eclipse.papyrus.manufacturing.ofbiz.createWorkEffort;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-09-08T11:16:57.457+02:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://ofbiz.apache.org/service/", name = "createWorkEffortPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CreateWorkEffortPortType {

    @WebMethod(action = "http://localhost:8080/manufacturing/control/SOAPService")
    public void createWorkEffort(
        @WebParam(partName = "map-Map", mode = WebParam.Mode.INOUT, name = "map-Map")
        javax.xml.ws.Holder<MapMap> mapMap
    );
}
