
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.eclipse.papyrus.manufacturing.ofbiz.createWorkEffort;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-09-08T11:16:57.444+02:00
 * Generated source version: 3.1.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "createWorkEffort",
                      portName = "createWorkEffortPort",
                      targetNamespace = "http://ofbiz.apache.org/service/",
                      wsdlLocation = "http://localhost:8080/manufacturing/control/SOAPService/createWorkEffort?wsdl",
                      endpointInterface = "org.eclipse.papyrus.manufacturing.ofbiz.createWorkEffort.CreateWorkEffortPortType")
                      
public class CreateWorkEffortPortImpl implements CreateWorkEffortPortType {

    private static final Logger LOG = Logger.getLogger(CreateWorkEffortPortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.eclipse.papyrus.manufacturing.ofbiz.createWorkEffort.CreateWorkEffortPortType#createWorkEffort(org.eclipse.papyrus.manufacturing.ofbiz.createWorkEffort.MapMap  mapMap )*
     */
    public void createWorkEffort(javax.xml.ws.Holder<MapMap> mapMap) { 
        LOG.info("Executing operation createWorkEffort");
        System.out.println(mapMap.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
