<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="exceptions" nsURI="http://www.eclipse.org/papyrus/2015/testframework/exceptions"
    nsPrefix="exceptions">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ForbiddenEditPartPermutation" eSuperTypes="#//TestConstraint">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="validate" ordered="false" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
        <eAnnotations source="redefines" references="#//TestConstraint/validate"/>
        <eParameters name="editPart" unique="false" lowerBound="1" upperBound="-1"
            eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
        <eParameters name="testClass" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
        <eParameters name="diagnostics" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDiagnosticChain"/>
      </contents>
    </eAnnotations>
    <eOperations name="test_classes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="body" value="testClass->forAll(conformsTo(_'org.eclipse.papyrus.uml.diagram.tests'::AbstractPapyrusTestCase.oclAsType(UML::Type)))"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="testClass->forAll(conformsTo(_'org.eclipse.papyrus.uml.diagram.tests'::AbstractPapyrusTestCase.oclAsType(UML::Type)))"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reasonKind" ordered="false"
        lowerBound="1" eType="#//ForbiddenReasonKind" defaultValueLiteral="invalid"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testClass" ordered="false"
        lowerBound="1" upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editPart" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//EditPartSpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestConstraint" abstract="true">
    <eOperations name="validate" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
      <eParameters name="editPart" unique="false" lowerBound="1" upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
      <eParameters name="testClass" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      <eParameters name="diagnostics" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDiagnosticChain"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" ordered="false"
        lowerBound="1" eType="#//TestExceptions" eOpposite="#//TestExceptions/constraint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omitOnFailure" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestExceptions">
    <eOperations name="validate" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
      <eParameters name="editPart" unique="false" lowerBound="1" upperBound="-1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
      <eParameters name="testClass" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      <eParameters name="diagnostics" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDiagnosticChain"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" ordered="false"
        upperBound="-1" eType="#//TestConstraint" containment="true" eOpposite="#//TestConstraint/container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ForbiddenReasonKind">
    <eLiterals name="invalid"/>
    <eLiterals name="failing" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that the permutation of edit-parts is forbidden because the tests generated would fail.&#xA;The system-under-test intends to support this permutation, but it does not work."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="unimplemented" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that the permutation of edit-parts is forbidden because the&#xA;system-under-test does not intend to support it, so generating tests&#xA;would be pointless (they would only fail)."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="interactive" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditPartSpec" abstract="true">
    <eOperations name="matches" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
      <eParameters name="editPart" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composite" ordered="false"
        eType="#//CompositeEditPartSpec" eOpposite="#//CompositeEditPartSpec/operand"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeEditPartSpec" eSuperTypes="#//EditPartSpec">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="matches" ordered="false" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
        <eAnnotations source="redefines" references="#//EditPartSpec/matches"/>
        <eParameters name="editPart" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
        lowerBound="1" eType="#//OperatorKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//EditPartSpec" containment="true"
        eOpposite="#//EditPartSpec/composite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorKind">
    <eLiterals name="and"/>
    <eLiterals name="or" value="1"/>
    <eLiterals name="not" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditPartRef" eSuperTypes="#//EditPartSpec">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="matches" ordered="false" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
        <eAnnotations source="redefines" references="#//EditPartSpec/matches"/>
        <eParameters name="editPart" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editPart" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.gmf.codegen/models/gmfgen.ecore#//GenCommonBase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnyEditPart" eSuperTypes="#//EditPartSpec">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="matches" ordered="false" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
        <eAnnotations source="redefines" references="#//EditPartSpec/matches"/>
        <eParameters name="editPart" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForbiddenEditPart" eSuperTypes="#//TestConstraint">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="validate" ordered="false" lowerBound="1"
          eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
        <eAnnotations source="redefines" references="#//TestConstraint/validate"/>
        <eParameters name="editPart" unique="false" lowerBound="1" upperBound="-1"
            eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
        <eParameters name="testClass" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
        <eParameters name="diagnostics" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDiagnosticChain"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editPart" ordered="false"
        lowerBound="1" eType="#//EditPartSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reasonKind" ordered="false"
        lowerBound="1" eType="#//ForbiddenReasonKind" defaultValueLiteral="invalid"/>
  </eClassifiers>
</ecore:EPackage>
