/**
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.textedit.port.xtext.generator;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class UmlPortGenerator /* implements IGenerator  */{
  public void doGenerate(final /* Resource */Object resource, final /* IFileSystemAccess */Object fsa) {
  }
}
