/**
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.alf.generator;

@SuppressWarnings("all")
public class AlfGenerator /* implements IGenerator  */{
  public void doGenerate(final /* Resource */Object resource, final /* IFileSystemAccess */Object fsa) {
  }
}
