/**
 *
 * $Id$
 */
package SoaML.validation;

import org.eclipse.uml2.uml.CollaborationUse;

/**
 * A sample validator interface for {@link SoaML.CollaborationUse}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CollaborationUseValidator {
	boolean validate();

	boolean validateBase_CollaborationUse(CollaborationUse value);
	boolean validateIsStrict(boolean value);
}
