/**
 *
 * $Id$
 */
package SoaML.validation;

import org.eclipse.uml2.uml.DataType;
import org.eclipse.uml2.uml.Signal;

/**
 * A sample validator interface for {@link SoaML.MessageType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MessageTypeValidator {
	boolean validate();

	boolean validateBase_Signal(Signal value);
	boolean validateEncoding(String value);
	boolean validateBase_Class(org.eclipse.uml2.uml.Class value);
	boolean validateBase_DataType(DataType value);
}
