/**
 *
 * $Id$
 */
package SoaML.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.uml2.uml.Comment;
import org.eclipse.uml2.uml.Signal;
import org.eclipse.uml2.uml.ValueSpecification;

/**
 * A sample validator interface for {@link SoaML.Milestone}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MilestoneValidator {
	boolean validate();

	boolean validateSignal(Signal value);
	boolean validateProgress(int value);
	boolean validateValue(EList<ValueSpecification> value);
	boolean validateBase_Comment(Comment value);
}
