/**
 *
 * $Id$
 */
package SoaML.validation;

import org.eclipse.uml2.uml.Interface;

/**
 * A sample validator interface for {@link SoaML.Provider}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProviderValidator {
	boolean validate();

	boolean validateBase_Class(org.eclipse.uml2.uml.Class value);
	boolean validateBase_Interface(Interface value);
}
